Drop support for HHVM
twigphp/Twig pull request #2478
Opened 2017-05-19 06:24 UTC by fabpot

2017-05-19 07:52 UTC, stof requested changes

2017-05-19 07:52 UTC, stof commented on .travis.yml
> -    - nightly
you should not remove testing on PHP nightly

2017-05-21 22:31 UTC, robfrawley commented
Shouldn't this be done aginst `2.x`, as this is basically a deprecation?

2017-05-22 05:26 UTC, fabpot commented
Doing it in 2.x would be the same. If we really want to "deprecate" HHVM, we would have to do it in 3.x, which is a no-go for me.

2017-05-22 05:48 UTC, merged

2017-05-23 01:02 UTC, robfrawley commented
Fair enough @fabpot. We've done the same in a few other projects I maintain because the situation was untenable, so I understand the motivation.