Support absolute paths when rendering a template
twigphp/Twig pull request #2505
Opened 2017-06-07 09:27 UTC by ShinDarth

2017-06-07 09:41 UTC, stof commented
@fabpot we should work on deprecating this pattern IMO, which was allowed due to internal implementation details of the filesystem loader but not intentionally supported (we actually even broke it in the past and reverted some changes to avoid BC breaks for people relying on this behavior).

2017-06-07 09:43 UTC, stof requested changes

2017-06-07 09:43 UTC, stof commented on lib/Twig/Loader/Filesystem.php
> +            return $name;
returning a name without the validation is a no-go. It is a security issue. This logic must go after the validation

2017-06-07 09:48 UTC, ShinDarth commented on lib/Twig/Loader/Filesystem.php
> +            return $name;
done

2017-07-22 07:35 UTC, fabpot commented
Can you add a test?

2017-07-22 13:10 UTC, ShinDarth commented
currently I'm on holiday but I can add the test as soon as I'll be back if my proposed change is acceptable

2018-01-30 11:14 UTC, stof commented
Btw, this also breaks the promise that Twig does not allow rendering things outside the configured template folders, which could introduce security issues. So I don't like this change.

2018-03-02 13:47 UTC, fabpot commented
I'm closing this pull request as I agree with @stof, we don't want to support absolute paths. It worked by chance but was never supposed to be supported.

2018-03-02 13:47 UTC, closed without merging