Add max value to random function
twigphp/Twig pull request #2698
Opened 2018-06-05 11:51 UTC by SpacePossum

2018-10-05 11:09 UTC, SpacePossum commented
couple of months in, any thoughts? :)

(happy to carry this PR for couple more though)

2019-01-14 08:06 UTC, fabpot requested changes
Looks good to me apart from some comments. Also, this should be rebased on 1.x as we are still adding all new features in the 1.x branch. Thank you.

2019-01-14 08:06 UTC, fabpot commented on lib/Twig/Extension/Core.php
>          return mt_rand();
Shouldn't we take `max` into account here?

2019-01-14 08:06 UTC, fabpot commented on lib/Twig/Extension/Core.php
> +        ;
should be on one line.

2019-01-14 08:06 UTC, fabpot commented on lib/Twig/Extension/Core.php
> +        return function_exists('random_int')
Can you add a comment about the PHP version it was added in so that we can remove the condition when we bump the min version?

2019-01-14 08:06 UTC, fabpot commented on lib/Twig/Extension/Core.php
> + * @param int|float|null                     $max    Max. value used when $values is an int or float
`Maximum value ...`

2019-01-14 08:06 UTC, fabpot commented on lib/Twig/Extension/Core.php
> +            $max = (int) $max;
Why do you cast to `int` here?

2019-01-14 08:06 UTC, fabpot commented on lib/Twig/Extension/Core.php
> +                $min = (int) $values;
I had a hard time figuring out why `$values` is casted to an `int` here. Can we make it more obvious? I have not tested, but I supposed it works well on all possible inputs.

2019-01-16 16:15 UTC, SpacePossum commented
For clarity about the last commit.
I've removed:
- selecting the random function to use; this can be part of a dedicated modernizing PR somewhere in the future
- the explicit casting; this can be handled when strict types gets enabled in the future in a dedicated PR

I also update the PHPDoc on request and rebased and retargeted to the 1.x branch

2019-02-15 03:08 UTC, fabpot requested changes

2019-02-15 03:08 UTC, fabpot commented on doc/functions/random.rst
> +* a random integer between 0 and the integer (or float) parameter (inclusive).
The `or float` part should be reverted, `mt_rand` accepts int only.

2019-03-05 08:02 UTC, fabpot approved these changes

2019-03-05 19:06 UTC, fabpot commented
Thank you @SpacePossum.

2019-03-05 19:06 UTC, merged

2019-03-05 22:54 UTC, SpacePossum commented
thanks @fabpot : )