Report the proper location for errors compiled in templates
twigphp/Twig pull request #2700
Opened 2018-06-06 18:29 UTC by stof

The `{% use %}` and `{% with %}` tags are adding some runtime checks triggering exceptions in the compiled template. This ensures that they get the proper location.
While the guessing was generally working fine for the `{% with %}` (and so this only makes the code faster), the guessing was not working for `{% use %}` due to the exception happening in the class constructor rather than on display (and so the guessing was finding the template which was triggering the load of the faulty template).

2018-06-06 18:29 UTC, stof commented
I will send a separate PR to 1.x, as it does not have `$this->source` in compiled templates AFAIK

2018-06-06 19:04 UTC, fabpot requested changes

2018-06-06 19:04 UTC, fabpot commented on lib/Twig/Node/Module.php
> +                        ->raw(".',")
missing space after the comma

2018-06-06 19:04 UTC, fabpot commented on lib/Twig/Node/With.php
> +                ->write("throw new Twig_Error_Runtime('Variables passed to the \"with\" tag must be a hash.',")
missing space after the comma

2018-06-06 19:04 UTC, fabpot commented on lib/Twig/Node/Module.php
> +                    ->raw(".'\" cannot be used as a trait.',")
missing space after the comma

2018-06-06 20:59 UTC, stof commented
@fabpot fixed.

2018-06-07 05:43 UTC, fabpot commented
Thank you @stof.

2018-06-07 05:43 UTC, merged