Enhances join filter for natural language join (i.e., "A, B and C")
twigphp/Twig pull request #2757
Opened 2018-09-28 15:30 UTC by LavaSlider

Simply adds a second optional parameter to the join filter that will be placed between the last two entries when generating the string. Since the filter only took one argument previously, this should be 100% backward compatible. Allows simple "first, second and third" string from an array. Compatible with any length input array.

2018-10-01 10:03 UTC, stof requested changes

2018-10-01 10:03 UTC, stof commented on lib/Twig/Extension/Core.php
> +    if( empty( (array) $value ) || is_null( $and ) || $and === $glue ) {
please perform the array casting only once

2018-10-01 10:03 UTC, stof commented on lib/Twig/Extension/Core.php
> +    if( empty( (array) $value ) || is_null( $and ) || $and === $glue ) {
The null check should use `null === $and` rather than `is_null()` according to the coding standards

2018-10-01 10:03 UTC, stof commented on lib/Twig/Extension/Core.php
> + * @param string $and   The separator for the last pair
this argument has `string|null` as type, not `string`

2018-12-16 10:42 UTC, fabpot commented
Thank you @LavaSlider.

2018-12-16 10:42 UTC, merged