hash literal property value shorthand
twigphp/Twig pull request #3002
Opened 2019-05-10 15:10 UTC by sukei

While doing some Twig templates recently. I was taking myself writing things like this:

```
{{ include('pagination.html.twig', { count: count, current_page: current_page, current_route: current_route }) }}
```
And was thinking about the ability of doing this:

```
{{ include('pagination.html.twig', { count, current_page, current_route }) }}
```

This is the purpose of this PR. This syntactic sugar comes from the JavaScript world (ES6) in the name of `Object Literal Property Value Shorthand` and It's very convenient to use.

2019-05-14 07:26 UTC, fabpot requested changes

2019-05-14 07:26 UTC, fabpot commented on src/ExpressionParser.php
> +            } else if ($value === null) {
CS: `} elseif (null === $value) {` (notice the removed whitespace between `else` and `if`) and the inversion of `null` and `$value`

2019-05-14 07:26 UTC, fabpot commented on src/ExpressionParser.php
> +                $key = new ConstantExpression($value = $token->getValue(), $token->getLine());
Here, this the key name, so what about renaming `$value` to `$keyName`?

2019-05-14 07:26 UTC, fabpot commented on test/Twig/Tests/ExpressionParserTest.php
> -            ['{{ {"a": "b", 2} }}'],
This should be kept and supported as this is valid.

2019-05-18 15:11 UTC, fabpot commented
I've just re-read some older issues and pull requests on the same topic (#2532, #502, #1019) to name a few). Similar notations were rejected in the past as it makes hashes looks like an array (`{ 'foo', 'bar' }` vs ``[ 'foo', 'bar' ]``), and that might confusing. Thanks for proposing.

2019-05-18 15:11 UTC, closed without merging

2019-05-19 15:05 UTC, sukei commented
Too bad :(. That's was a really convenient syntax (essentially for frontend developers/designers who are used to it thanks to ES6).

2019-06-28 12:43 UTC, carlcs commented
https://symfony.com/blog/twig-adds-filter-map-and-reduce-features

I’ve just became aware of the newly added filter, map and reduce filters, and seeing how the syntax is borrowed from ES6 I was again reminded of this PR.

@fabpot can you please give this another thought. Seeing the amount of issues, votes and PRs leaves me with the impression that this feature has the potential to make many people happy.

2019-06-28 15:09 UTC, sukei commented
I have the same feeling.