In twig_array_filter, throw a RuntimeError instead of a raw TypeError
twigphp/Twig pull request #3341
Opened 2020-05-28 15:55 UTC by thijzert

If a template accidentally performs `|filter(...)` on a variable that isn't traversable (e.g. `null`), the calling code will encouter the raw `TypeError` that results from Twig trying to construct an `IteratorIterator` on that variable. This means that context information (e.g., in which exact template the error occurred, and on which line) is discarded, which makes it very difficult to debug your templates.

This commit adds code to throw a `RuntimeError` if Twig encounters a situation where there's no valid way to filter an array.

2020-06-07 10:02 UTC, guilliamxavier commented
There's already #3326 that has been merged in `1.x` but not into `2.x`/`3.x`.

Also, what about `twig_array_map` and `twig_array_reduce`?

2020-06-07 19:46 UTC, thijzert commented
I guess I should use `|reduce()` more - it has the same problem. I've added a fix for it.

`twig_array_map` already fails with a RuntimeError in a way that's consistent with my subjective expectations, so I've added a unit test to fix the behaviour in place.

2020-06-08 08:29 UTC, guilliamxavier commented
Actually `twig_array_map(null, fn ($x) => $x)` doesn't throw an exception per se, just emits a Warning "Invalid argument supplied for foreach()", that I suppose is then converted to a RuntimeError by some error handler... But indeed not a TypeError either way ;)

Anyway `$array instanceof \Traversable || $array instanceof \Iterator` is redundant since `interface Iterator extends Traversable` (see e.g. `twig_array_column`)

2020-06-08 08:36 UTC, thijzert commented
> Actually `twig_array_map(null, fn ($x) => $x)` doesn't throw an exception per se, just emits a Warning "Invalid argument supplied for foreach()", that I suppose is then converted to a RuntimeError by some error handler.

Ah, that makes sense.

2020-06-08 08:58 UTC, guilliamxavier commented on src/Extension/CoreExtension.php
> +        throw new RuntimeError(sprintf('An array filter only works with arrays or "Traversable", got "%s" as first argument.', \gettype($array)));
```suggestion
        throw new RuntimeError(sprintf('The filter filter only works with arrays or "Traversable", got "%s" as first argument.', \gettype($array)));
```
(or maybe
```suggestion
        throw new RuntimeError(sprintf('The "filter" filter only works with arrays or "Traversable", got "%s" as first argument.', \gettype($array)));
```
to mitigate the repetition)

2020-06-08 08:58 UTC, guilliamxavier commented on src/Extension/CoreExtension.php
> +            throw new RuntimeError(sprintf('An array filter only works with arrays or "Traversable", got "%s" as first argument.', \gettype($array)));
```suggestion
            throw new RuntimeError(sprintf('The reduce filter only works with arrays or "Traversable", got "%s" as first argument.', \gettype($array)));
```

2020-08-23 12:09 UTC, fabpot commented
Can you rebase on 1.x and remove the check in twig_array_filter as it is redundant?

2020-08-23 12:39 UTC, thijzert commented
Some would say "redundant," some would say "preemptive regression test," but sure, no problem.

2020-08-23 12:50 UTC, fabpot requested changes

2020-08-23 12:50 UTC, fabpot commented on src/Extension/CoreExtension.php
> +    if (!$array instanceof \Traversable) {
This test must be removed, the same test is already done line 1698.

2020-08-23 12:51 UTC, fabpot commented
@thijzert I made a comment to make myself clearer. The test was fine and can be re-added :)

2020-08-23 12:56 UTC, thijzert commented
Ah, yes, I see the confusion now.

2020-08-23 13:05 UTC, thijzert commented on src/Extension/CoreExtension.php
> +    if (!$array instanceof \Traversable) {
Done.

2020-08-23 14:40 UTC, fabpot commented
Thank you @thijzert.

2020-08-23 14:40 UTC, merged