Enhancement: Introduce DOCtor-RST config + GithubAction
twigphp/Twig pull request #3417
Opened 2020-10-29 11:52 UTC by OskarStark

2020-10-29 12:11 UTC, derrabus requested changes

2020-10-29 12:11 UTC, derrabus commented on doc/tags/for.rst
> +.. code-block:: html+wig
This does not look right.

2020-10-29 12:11 UTC, derrabus commented on doc/tags/macro.rst
> +.. code-block:: html+wig
Same.

2020-10-29 12:23 UTC, OskarStark commented on doc/tags/macro.rst
> +.. code-block:: html+wig
```suggestion
.. code-block:: html+twig
```

2020-10-29 12:23 UTC, OskarStark commented on doc/tags/for.rst
> +.. code-block:: html+wig
Thanks, fixed!

2020-10-29 12:24 UTC, OskarStark commented on doc/tags/macro.rst
> +.. code-block:: html+wig
Thanks fixed

2020-11-03 14:49 UTC, OskarStark commented on doc/.doctor-rst.yaml
> +        min_version: '3.0'
```suggestion
        min_version: '3.0'

```

2020-11-06 07:11 UTC, fabpot commented
Thank you @OskarStark.

2020-11-06 07:11 UTC, merged