Add "html_attributes" twig filter for easiely write attributes as objects
twigphp/Twig pull request #3760
Opened 2022-10-14 08:26 UTC by alexander-schranz

Example usage:

```twig

{# required #}
{%- set text = text -%}

{# optional #}
{%- set id = id|default -%}
{%- set skin = skin|default('primary') -%}
{%- set type = type|default('button') -%}
{%- set disabled = disabled|default -%}

{% set attributes = {
    'id': id,
    'class': html_classes(
        'c-button',
        {
            'c-button--primary': skin == 'primary',
            'c-button--secondary': skin == 'secondary',
            'c-button--borderless': skin == 'borderless',
        },
    ),
    'type': type,
    'disabled': disabled,
} %}

<button {{ attributes|html_attributes }}>
    {{- text -}}
</button>
```

## TODO

 - [x] Escape Value
 - [ ] Add Test Case

2022-10-14 08:47 UTC, stof requested changes

2022-10-14 08:47 UTC, stof commented on extra/html-extra/HtmlExtension.php
> +                'html_attributes',
this looks more like a function than a filter to me

2022-10-14 08:47 UTC, stof commented on extra/html-extra/HtmlExtension.php
> +            $htmlAttributes[] = $key . '="' . twig_escape_filter($environment, $value, 'html_attr') . '"';
keys must be escaped too

2022-10-14 08:47 UTC, stof commented on extra/html-extra/HtmlExtension.php
> +     * @param array{string, string|bool|int|float|null} $attributes
wrong type. `array{string, string|bool|int|float|null}` means an array with 2 elements, with index 0 being a string and index 1 being `string|bool|int|float|null`. Instead, you should use `array<string, string|bool|int|float|null>`

2023-12-07 09:20 UTC, mpdude commented
Incidentally I made a very similar suggestion at https://github.com/twigphp/Twig/issues/3907 with a PoC PR at https://github.com/twigphp/Twig/pull/3930.

Would be great if you could 👀 and maybe we can join efforts.

2024-09-26 20:00 UTC, fabpot commented
Closing in favor of #3930 (which has the `html_attr_merge` function in addition to this)

2024-09-26 20:00 UTC, closed without merging

2024-09-27 10:41 UTC, alexander-schranz commented
Make sense. Thx @mpdude 👍