Fix premature loop exit in Security Policy lookup of allowed methods/properties
twigphp/Twig pull request #3873
Opened 2023-08-30 18:24 UTC by YSaxon

The current security policy logic exits too soon when checking permissions for allowed classes and their methods/properties, causing false negatives in situations involving classes related by inheritance.

Consider the following configuration:

```
'methods' => [
  'App\BasicCollection' => ['sortAlphabetically'],
  'App\AdvancedCollection'=> ['sortByTimestamp'],
],
```
where `AdvancedCollection` is a subclass of `BasicCollection`, and `mylist` is an instance of `AdvancedCollection`

If you try to call `{{ mylist.sortByTimestamp() }}`, the current code will first match `mylist` against `App\BasicCollection`. Since `sortByTimestamp` is not an allowed method for `App\BasicCollection`, the code will exit the loop and incorrectly deny access. It will never get to checking `App\AdvancedCollection`.

Note that reordering classes in the config can't solve this issue. If you flipped the order, then it would fail for `{{ mylist.sortAlphabetically() }}` instead.

This pull request fixes the issue by only exiting the loop early when both the class and method/property match.

2023-09-14 15:52 UTC, YSaxon commented
I just modified the pull request to point to the 2.x branch instead of the 3.x branch.

2023-10-17 17:10 UTC, YSaxon commented
@fabpot if you can take a look at this one as well please

2023-10-20 15:58 UTC, fabpot commented
@YSaxon Can you add a test to ensure that we won't introduce a regression later on.

2023-10-26 17:42 UTC, fabpot requested changes

2023-10-26 17:42 UTC, fabpot commented on src/Sandbox/SecurityPolicy.php
> +            $class = $obj::class;
Can you revert the changes unrelated to this PR? Sometimes fabbot is just wrong ;)
Basically, reverting this commit.

2023-10-26 18:33 UTC, YSaxon commented on src/Sandbox/SecurityPolicy.php
> +            $class = $obj::class;
That's why I split the commit in two, to make sure it would be easy to revert if necessary.

2023-10-27 00:37 UTC, fabpot commented
Thank you @YSaxon.

2023-10-27 00:37 UTC, merged