add docs & links
twigphp/Twig pull request #3941
Opened 2023-12-12 14:32 UTC by lacpandore

2023-12-12 20:57 UTC, GromNaN commented on doc/filters/date.rst
> +* ``format``:   The date format. Default format is 'F j, Y H:i', which will render 'Januar 11, 2024 15:17'
```suggestion
* ``format``:   The date format. Default format is 'F j, Y H:i', which will render 'January 11, 2024 15:17'
```

2023-12-12 20:57 UTC, GromNaN commented on doc/filters/slice.rst
> +* ``preserve_keys``: Whether to preserve key or not (when the input is an array), by default the value is false.
```suggestion
* ``preserve_keys``: Whether to preserve key or not (when the input is an array), by default the value is ``false``.
```

2023-12-12 21:05 UTC, GromNaN approved these changes

2023-12-13 12:02 UTC, fabpot requested changes

2023-12-13 12:02 UTC, fabpot commented on doc/filters/batch.rst
> +If you choose to set the third parameter 'preserve_keys' to false, the keys will be reset in each loop.
```suggestion
If you choose to set the third parameter ``preserve_keys`` to ``false``, the keys will be reset in each loop.
```

2023-12-13 12:02 UTC, fabpot commented on doc/filters/batch.rst
> +* ``preserve_keys``: Whether to preserve keys or not, by defaut to true
```suggestion
* ``preserve_keys``: Whether to preserve keys or not (defaults to ``true``)
```

2023-12-13 12:02 UTC, fabpot commented on doc/filters/date.rst
> +it by explicitly specifying a supported `timezones`_:
```suggestion
it by explicitly specifying a supported `timezone`_:
```

2023-12-13 12:02 UTC, fabpot commented on doc/filters/date.rst
> +.. _`timezones`:            https://www.php.net/manual/en/timezones.php
```suggestion
.. _`timezone`:            https://www.php.net/manual/en/timezones.php
```

2023-12-13 12:02 UTC, fabpot commented on doc/filters/date.rst
> +* ``format``:   The date format. Default format is 'F j, Y H:i', which will render 'January 11, 2024 15:17'
```suggestion
* ``format``:   The date format (default format is ``F j, Y H:i``, which will render as ``January 11, 2024 15:17``)
```

2023-12-13 12:02 UTC, fabpot commented on doc/filters/slice.rst
> +The argument `preserve_keys` is used to reset the index during the loop.
```suggestion
The argument ``preserve_keys`` is used to reset the index during the loop.
```

2023-12-14 07:17 UTC, fabpot commented
Thank you @lacpandore.

2023-12-14 07:17 UTC, merged