Add new "find" filter
twigphp/Twig pull request #3963
Opened 2024-01-13 23:42 UTC by smnandre

This filter returns the first _value_ matching the given arrow function or null

Attempt to solve #3962 

(open to any feedback)

2024-01-13 23:45 UTC, smnandre commented
(failures unrelated with this filter)

2024-08-02 22:43 UTC, smnandre commented
Added documentation

(fabbot still complaining on a false-positive)

2024-08-03 11:52 UTC, fabpot requested changes
Can you also update the CHANGELOG file?

2024-08-03 11:52 UTC, fabpot commented on doc/filters/find.rst
> +==========
```suggestion
========
```

2024-08-03 11:52 UTC, fabpot commented on doc/filters/find.rst
> +The ``find`` returns the first element of a sequence matching an arrow
```suggestion
The ``find`` filter returns the first element of a sequence matching an arrow
```

2024-08-03 11:52 UTC, fabpot commented on doc/filters/find.rst
> +Note that the arrow function has access to the current context.
Maybe we can give an example on how to do it.

2024-08-03 11:52 UTC, fabpot commented on doc/filters/find.rst
> +
You should add the following:

```rst
.. versionadded:: 3.11

    The ``find`` function was added in Twig 3.11.
```

2024-08-03 11:52 UTC, fabpot commented on src/Extension/CoreExtension.php
> +            new TwigFilter('find', [self::class, 'arrayFind'], ['needs_environment' => true]),
```suggestion
            new TwigFilter('find', [self::class, 'find'], ['needs_environment' => true]),
```

2024-08-03 13:05 UTC, smnandre commented
> Can you also update the CHANGELOG file?

Good. Any other need in documentation or tests ?

2024-08-04 11:39 UTC, fabpot commented
Thank you @smnandre.

2024-08-04 11:39 UTC, merged