[RFC] Multiline {## Comment Block ##}
twigphp/Twig pull request #3986
Opened 2024-01-26 00:25 UTC by smnandre

I started to work on this feature, following @ThomasLandauer  comment in #3951 (and previously discussed in #2897)

So this PR is a starting point to discuss implementation, any particularities, specific behaviours, etc.

The idea is that anything between  `{##` and `##}`  would be parsed as a comment (and thus ignored)

```twig
Hello {## foo bar 
Foo
Bar {# Bar #}
Foo ##} Hello
```

would render

```html
Hello  Hello
```

2024-01-26 11:03 UTC, stof requested changes

2024-01-26 11:03 UTC, stof commented on tests/LexerTest.php
> +        $this->addToAssertionCount(1);
no need for a dummy assertion here, as there is an actual assertion just above.

2024-01-26 11:03 UTC, stof commented on tests/LexerTest.php
> +    public function testMultiLineCommentNestedBlock()
this test does not seem to have any nested block.

2024-01-26 11:03 UTC, stof commented on tests/LexerTest.php
> +    public function testMultiLineCommentBlockWithInlineBLocks()
this seems to be about inline comments

2024-01-26 20:30 UTC, smnandre commented
Thank you for this first feedback @stof

2024-02-09 22:12 UTC, smnandre commented
Is this something really needed / asked for ? 

Just to be sure it is worth the time needed to refine this PR, add documentation, think how to handle BC, ....

2024-02-10 08:56 UTC, fabpot commented
As far as I know, this syntax is not supported by any other language similar to Twig (Jinja and the like), so I'm not sure if the use cases are worth the added complexity in core.

2024-02-10 09:08 UTC, smnandre commented
Well let's close then :)

2024-02-10 09:08 UTC, closed without merging

2024-02-11 15:23 UTC, c33s commented
i would have been happy to see this feature finally. it helps to easily comment out blocks of text which have comments inside and preserving them after you uncomment the block again.