Mark implicit macro argument default values as such with an attribute
twigphp/Twig pull request #4010
Opened 2024-03-16 15:45 UTC by drjayvee

This change causes no difference to compiled templates or to macro argument semantics.

Consider the following macro:
```twig
{% macro marco(po, lo = null) %}{% endmacro %}
```

With this change, the `ConstantExpression` for argument `po` will have an attribute `isImplicit`, whose value will be `true`. (Note that `lo` will not have that attribute.)

This allows node visitors to distinguish between arguments that do and those that do not have explicit default values even if the value is `null`.

This is useful for [static code analysis](https://github.com/twigphp/Twig/issues/4003).

For example, a static analysis tool might consider arguments with no explicit default value as non-optional.

2024-03-16 15:48 UTC, drjayvee commented
Similar to #4009, this is a prerequisite for a desired static analysis inspection in [TwigStan](https://github.com/alisqi/twig-stan/).

I can extend this feature by adding this attribute to *every* function/macro argument to make it more consistent.

2024-08-19 18:23 UTC, fabpot commented on src/ExpressionParser.php
> +                    $value->setAttribute('isImplicit', true);
```suggestion
                    $value->setAttribute('is_implicit', true);
```

2024-08-19 18:23 UTC, fabpot commented on tests/ParserTest.php
> +        );
All assertions should be one-liners (and use `$this->assertTrue()` to be consistent with the code base).

2024-08-19 18:23 UTC, fabpot commented on tests/ParserTest.php
> +        $template = '{% macro marco (po, lo = null) %}{% endmacro %}';
As the default value is `null` anyway, what about using a non-null value for `lo` so that the test is more relevant?

2024-08-20 10:09 UTC, drjayvee commented on tests/ParserTest.php
> +        $template = '{% macro marco (po, lo = null) %}{% endmacro %}';
Absolutely!

2024-08-20 10:11 UTC, drjayvee commented
@fabpot thanks for the review. The latest commit includes all your suggestions.

2024-08-27 10:56 UTC, drjayvee commented
@fabpot since you're working on Twig these days, could you please have another look at this PR? 😊

2024-08-27 11:14 UTC, fabpot requested changes
LGTM

2024-08-27 11:14 UTC, fabpot commented on tests/ParserTest.php
> +        $lexer = new Lexer(new Environment($this->createMock(LoaderInterface::class)));
```suggestion
        $lexer = new Lexer(new Environment(new ArrayLoader()));
```

2024-08-27 11:21 UTC, fabpot commented
Thank you @drjayvee.

2024-08-27 11:22 UTC, fabpot commented
Merged.

2024-08-27 11:22 UTC, closed without merging