User first class callable syntax
twigphp/Twig pull request #4137
Opened 2024-07-13 17:30 UTC by fabpot

2024-07-13 19:49 UTC, GromNaN requested changes

2024-07-13 19:49 UTC, GromNaN commented on extra/html-extra/HtmlExtension.php
> +            new TwigFunction('html_classes', self::class::htmlClasses(...)),
There is many changes like this:
```suggestion
            new TwigFunction('html_classes', self::htmlClasses(...)),
```

2024-07-14 08:47 UTC, GromNaN approved these changes
For the failing test, you can fix `Twig\Parser::subparse()` with something like this:

```php
if (\is_array($test) && isset($test[0]) && $test[0] instanceof TokenParserInterface) {
    $e->appendMessage(\sprintf(' (expecting closing tag for the "%s" tag defined near line %s).', $test[0]->getTag(), $lineno));
} elseif ($test instanceof \Closure && is_subclass_of(($r = new \ReflectionFunction($test))->getClosureScopeClass()->getName(), TokenParserInterface::class)) {
    $e->appendMessage(\sprintf(' (expecting closing tag for the "%s" tag defined near line %s).', $r->getClosureThis()->getTag(), $lineno));
}
```

2024-07-14 12:02 UTC, fabpot commented
> For the failing test, you can fix `Twig\Parser::subparse()` with something like this:
> 
> ```
> $tokenParser = match (true) {
>     \is_array($test) => $test[0],
>     $test instanceof \Closure => (new \ReflectionFunction($test))->getClosureThis(),
>     default => null,
> };
> if ($tokenParser instanceof TokenParserInterface) {
>     $e->appendMessage(\sprintf(' (expecting closing tag for the "%s" tag defined near line %s).', $tokenParser->getTag(), $lineno));
> }
> ```

I have added native support instead.

2024-07-14 12:04 UTC, merged