Add support for named arguments on special functions
twigphp/Twig pull request #4173
Opened 2024-08-05 14:59 UTC by fabpot

2024-08-06 09:43 UTC, stof requested changes

2024-08-06 09:43 UTC, stof commented on src/ExpressionParser.php
> +        } elseif (count($arguments) < $required) {
this check is not enough when using named arguments. For instance, `attribute` has 2 required arguments and 1 optional argument. If I pass `variable` and `arguments`, I still don't have less arguments than the number of required arguments, but I don't fill all required arguments.

2024-08-12 05:12 UTC, smnandre commented on src/ExpressionParser.php
> +            throw new SyntaxError(sprintf('Not enough arguments for %s "%s" (it requires at least "%s").', $callType, $callName, implode('", ', array_slice($names, 0, $required))), $line, $this->pars
```suggestion
            throw new SyntaxError(sprintf('Not enough arguments for %s "%s" (it requires at least "%s").', $callType, $callName, implode('", "', array_slice($names, 0, $required))), $line, $this->parser->getStream()->getSourceContext());
```

2024-08-12 05:12 UTC, smnandre commented on src/ExpressionParser.php
> +                    throw new SyntaxError(\sprintf('Unexpected argument "%s" for %s "%s" (expecting one of "%s").', $name, $callType, $callName, implode('", ', $names)), $line, $this->parser->getStre
```suggestion
                    throw new SyntaxError(\sprintf('Unexpected argument "%s" for %s "%s" (expecting one of "%s").', $name, $callType, $callName, implode('", "', $names)), $line, $this->parser->getStream()->getSourceContext());
```

2024-08-12 05:14 UTC, smnandre commented on tests/Fixtures/functions/attribute_with_wrong_args.test
> +Twig\Error\SyntaxError: Unexpected argument "var" for function "attribute" (expecting one of "variable", attribute", arguments") in "index.twig" at line 2.
```suggestion
Twig\Error\SyntaxError: Unexpected argument "var" for function "attribute" (expecting one of "variable", "attribute", "arguments") in "index.twig" at line 2.
```

2024-08-16 06:19 UTC, fabpot commented on src/ExpressionParser.php
> +        } elseif (count($arguments) < $required) {
Fixed

2024-08-16 20:50 UTC, merged