Use CPP in RuntimeLoader folder
twigphp/Twig pull request #4228
Opened 2024-08-24 08:34 UTC by andreybolonin

2024-08-24 08:58 UTC, fabpot reviewed
Would you like to update the full code base?

2024-08-24 08:58 UTC, fabpot commented on src/RuntimeLoader/ContainerRuntimeLoader.php
> +    public function __construct(private ContainerInterface $container)
```suggestion
    public function __construct(
        private ContainerInterface $container,
    )
```

2024-08-24 09:05 UTC, andreybolonin commented
@fabpot ok, no problem )

2024-08-24 11:44 UTC, smnandre commented
@fabpot regarding the fabbot false positive on deprecation messages, should we add a check on "symfony/symfoy" on the "DeprecationMessageChecker" ?  Or is this something that can be configured ?

2024-08-29 10:01 UTC, fabpot requested changes

2024-08-29 10:01 UTC, fabpot commented on src/Extension/SandboxExtension.php
> -    public function isSandboxedGlobally(): bool
Must be reverted

2024-08-29 10:01 UTC, fabpot commented on src/Extension/SandboxExtension.php
>      {
CS fix for all such changes:

```suggestion
    ) {
```

2024-08-29 10:01 UTC, fabpot commented on src/TemplateWrapper.php
> +        private Template $template
```suggestion
        private Template $template,
```

2024-08-29 10:01 UTC, fabpot commented on src/Token.php
> +        private int $lineno
```suggestion
        private int $lineno,
```

2024-08-29 10:01 UTC, fabpot commented on src/TokenStream.php
> +        private ?Source $source = null
```suggestion
        private ?Source $source = null,
```

2024-08-29 12:06 UTC, fabpot commented on src/Extension/SandboxExtension.php
> -        return $this->sandboxedGlobally || $this->sandboxed || $this->isSourceSandboxed($source);
The two properties are still needed IIUC.

2024-08-29 12:06 UTC, fabpot commented on src/Extension/SandboxExtension.php
> +        private bool $sandboxed = false,
```suggestion
        private bool $sandboxedGlobally = false,
```
?

2024-08-29 13:24 UTC, stof requested changes

2024-08-29 13:24 UTC, stof commented on src/Cache/FilesystemCache.php
> +        private string $directory,
This should not use a promoted property as the value assigned in it is not the argument directly.

2024-08-29 13:24 UTC, stof commented on src/Markup.php
> +        private $content,
Same here as the constructor does not assign the argument itself.

2024-08-29 13:24 UTC, stof commented on src/Markup.php
> +        private $charset,
The charset must be `?string`

2024-08-29 13:24 UTC, stof commented on src/NodeVisitor/OptimizerNodeVisitor.php
> +        private int $optimizers = -1,
Why making it a promoted properties when the constructor still assigns it separately ? This makes no sense as it means the constructor assigns it twice.

2024-08-29 13:50 UTC, fabpot commented on src/NodeVisitor/OptimizerNodeVisitor.php
> +        private int $optimizers = -1,
Line 69 (`$this->optimizers = $optimizers;`) should be removed

2024-08-29 13:51 UTC, fabpot commented on src/Cache/FilesystemCache.php
> +        private string $directory,
I agree, let's revert cases where we need to do the assignment in the constructor.

2024-08-29 14:28 UTC, fabpot requested changes

2024-08-29 14:28 UTC, fabpot commented on src/Extension/SandboxExtension.php
> -    private $sandboxed;
This is still needed

2024-08-29 17:29 UTC, fabpot commented
Thank you @andreybolonin.

2024-08-29 17:29 UTC, merged