Deprecate the spaceless filter
twigphp/Twig pull request #4236
Opened 2024-08-26 12:39 UTC by fabpot

Closes #3576

2024-08-26 13:46 UTC, stof requested changes
This filter should be marked as deprecated in the filter definition, so that using the filter reports the deprecation at compile time (and so that the linter also reports it)

2024-08-26 13:46 UTC, stof commented on src/Extension/CoreExtension.php
> +        trigger_deprecation('twig/twig', '3.12', 'The "spaceless" filter is deprecated.');
Do we need a runtime deprecation for each usage of the filter ? can't we rely only on the compile-time deprecation instead ?

2024-08-26 13:47 UTC, stof commented on src/Extension/CoreExtension.php
> +        trigger_deprecation('twig/twig', '3.12', 'The "spaceless" filter is deprecated.');
OK, actually, the compile-time deprecation is not implemented.

2024-08-26 14:25 UTC, fabpot commented on src/Extension/CoreExtension.php
> +        trigger_deprecation('twig/twig', '3.12', 'The "spaceless" filter is deprecated.');
Indeed, as the function is `@internal`, let's use the built-in deprecation feature. Code updated accordingly.

2024-08-26 14:51 UTC, stof approved these changes

2024-08-26 15:00 UTC, merged

2025-03-03 23:26 UTC, ttk commented
I didn't find any good examples of how to replace `spaceless` with the existing whitespace controls.  So here's what I did:

```twig
{% apply spaceless %}
  <span>1</span>
  <span>2</span>
  <span>3</span>
{% endapply %}
```

To rewrite this without spaceless, I used `{{ }}` with a null condition and the appropriate whitespace controls:
```twig
  <span>1</span>{{ null -}}
  <span>2</span>{{ null -}}
  <span>3</span>
```

I experimented with other "null" conditions, and the following also work: `{{ '' -}}` , `{{ "" -}}` , and `{{ false -}}`, but I find `{{ null -}}` to be my personal preference.

Not sure if there is a better syntax to handle this?  It might be worth adding this example to the docs?

2025-03-04 09:53 UTC, stof commented
@ttk the shortest solution (and most efficient by disappearing entirely at runtime) is to use a comment to hold the whitespace control: `{# -#}`

2025-03-04 16:12 UTC, ttk commented
@stof Thanks, that is exactly what I was looking for!   I honestly didn't know that whitespace control worked on comments as well but after re-reviewing the docs, I see a single example shown [here](https://twig.symfony.com/doc/3.x/templates.html#whitespace-control).