Prepare IntegrationTestCase for static data providers
twigphp/Twig pull request #4266
Opened 2024-09-03 07:08 UTC by derrabus

Data providers need to be static in PHPUnit 11. Because of this, I'd like to declare the two methods we use as data providers in `IntegrationTestCase` as static in 4.0. This PR prepares that change:

* The non-static `getFixturesDir()` method is replaced with a static `getFixturesDirectory()`.
* Both methods `getTests()` and `getLegacyTests()` are marked as final, so we can declare them static in the next major.

This however means that we're delaying PHPUnit 11 compatibility of integration tests to Twig 4.0. If that's too late for us, we could deprecate the whole `IntegrationTestCase` in favor of a compatible replacement. That's a bigger change, but I would work on it if you think it's worth it.

2024-09-03 07:25 UTC, derrabus commented
The failures in the extra packages happen because we pull a version of Twig as dependency that does not include my changes. How do we deal with this kind of failure on this repo?

2024-09-03 10:11 UTC, stof commented
@derrabus accept it for now, as it will be resolved after the merge-up in the 4.x branch.

2024-09-03 10:13 UTC, stof requested changes

2024-09-03 10:13 UTC, stof commented on CHANGELOG
> + * Deprecate not overriding `Twig\Test\IntegrationTestCase::getFixturesDirectory()`, this method will be final in 4.0
```suggestion
 * Deprecate not overriding `Twig\Test\IntegrationTestCase::getFixturesDirectory()`, this method will be abstract in 4.0
```

2024-09-03 10:33 UTC, derrabus commented on CHANGELOG
> + * Deprecate not overriding `Twig\Test\IntegrationTestCase::getFixturesDirectory()`, this method will be final in 4.0
Good catch, thank you.

2024-09-03 11:36 UTC, fabpot commented
Having PHPUnit 11 support only in 4.0 sounds good to me.

2024-09-03 20:17 UTC, fabpot commented
Thank you @derrabus.

2024-09-03 20:17 UTC, merged

2025-01-10 22:04 UTC, williamdes commented
The documentation example is missing an update https://github.com/twigphp/Twig/blob/4.x/doc/advanced.rst#testing-an-extension

2025-01-10 22:10 UTC, williamdes commented on doc/deprecated.rst
> +  ``Twig\Test\IntegrationTestCase`` are considered final als of Twig 3.13.
typo

2025-01-10 22:16 UTC, GromNaN commented
@williamdes Would you like to open a PR to improve documentation?

2025-01-10 22:23 UTC, williamdes commented
> @williamdes Would you like to open a PR to improve documentation?

🇫🇷 I will try soon :)

2026-01-22 08:56 UTC, williamdes commented
> @williamdes Would you like to open a PR to improve documentation?

Update: I am trying to cleanup my TODO lists. I will not be the one making the doc update :/