[Doc] Document about `html` and `html_attr` strategies
twigphp/Twig pull request #4324
Opened 2024-09-19 09:58 UTC by Kocal

Ref #4322

2024-09-19 21:15 UTC, fabpot commented on doc/filters/escape.rst
> +    to quote the HTML attribute value and use ``html`` escaping strategy.
```suggestion
    to quote the HTML attribute value and use the ``html`` escaping strategy.
```

2024-09-20 11:09 UTC, Kocal commented on doc/filters/escape.rst
> +    to quote the HTML attribute value and use ``html`` escaping strategy.
Done

2024-09-20 18:20 UTC, fabpot requested changes

2024-09-20 18:20 UTC, fabpot commented on doc/filters/escape.rst
> +    escape a **dynamic HTML attribute name**.
```suggestion
    escape a **dynamic HTML attribute name**:
```

2024-09-20 18:20 UTC, fabpot commented on doc/filters/escape.rst
> +    to quote the HTML attribute value and use the ``html`` escaping strategy.
```suggestion
    to quote the HTML attribute value and use the ``html`` escaping strategy:
```

2024-09-20 18:20 UTC, fabpot commented on doc/filters/escape.rst
> +    It can also be used for escaping **dynamic HTML attribute value** if
```suggestion
    It can also be used for escaping a **dynamic HTML attribute value** if 
```

2024-09-20 18:20 UTC, fabpot commented on doc/filters/escape.rst
> +        {# is equivalent to, but is less performant #}
Let's add a newline above

2024-09-20 18:20 UTC, fabpot commented on doc/filters/escape.rst
> +* ``html_attr``: escapes a string for the **HTML attribute** context, **without quotes** around HTML attribute values.
Can you cut at around 80 chars?

2024-09-20 18:20 UTC, fabpot commented on doc/filters/escape.rst
> +* ``html``: escapes a string for the **HTML body** context, or for HTML attributes values **inside quotes**.
Can you cut at around 80 chars?

2024-09-20 18:35 UTC, Kocal commented
@fabpot it should be better now

2024-09-21 06:07 UTC, fabpot commented
Thank you @Kocal.

2024-09-21 06:07 UTC, merged