adds support for invoking closures
twigphp/Twig pull request #4501
Opened 2024-12-12 13:57 UTC by faizanakram99

- fixes #3848

2024-12-12 13:58 UTC, faizanakram99 commented
@fabpot errors are unrelated

2024-12-12 14:20 UTC, fabpot requested changes

2024-12-12 14:20 UTC, fabpot commented on tests/TemplateTest.php
> +        };
```suggestion
        // test for Closure::__invoke()
        $closure = fn (): string => 'closure called';
```

2024-12-12 14:22 UTC, fabpot commented on tests/TemplateTest.php
> +
Now that I see it, maybe we can even inline everything!

```suggestion
        $tests[] = [true, 'closure called', fn (): string => 'closure called', '__invoke', [], $anyType];
```

2024-12-12 14:29 UTC, fabpot commented
Last comment and I think we're good: can you add an item in the CHANGELOG file?

2024-12-12 14:31 UTC, nicolas-grekas approved these changes
LGTM
I'd suggest opening an issue on php-src also, get_class_methods() should return __invoke to me (and other non static methods BTW).

2024-12-12 14:41 UTC, faizanakram99 commented
> Last comment and I think we're good: can you add an item in the CHANGELOG file?

Done

2024-12-12 14:48 UTC, faizanakram99 commented
> LGTM I'd suggest opening an issue on php-src also, get_class_methods() should return __invoke to me (and other non static methods BTW).

Done https://github.com/php/php-src/issues/17126

2024-12-12 15:13 UTC, lowwa132 reviewed
Thank you for the PR @faizanakram99

2024-12-12 15:32 UTC, fabpot requested changes
For PHP 8.0, we need to check that line 1742, we not calling `isset($object->$item)` for Closure as it does not work.

2024-12-12 15:32 UTC, fabpot commented on tests/TemplateTest.php
> +        $tests[] = [true, 'closure called', fn (): string => 'closure called', '__invoke', [], $anyType];
Let's add another test:

```
$tests[] = [true, 'closure called', fn (): string => 'closure called', '__invoke', [], $methodType];
```

2024-12-14 19:06 UTC, fabpot commented
Thank you @faizanakram99.

2024-12-14 19:06 UTC, merged